name: Render.com Deploy

on:
  pull_request: {}
  push:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_WEBHOOK }}
        run: |
          curl "$deploy_url"
